---
title: "Calendars"
output:
  html_document:
    df_print: paged
date: "2026-10-01"
---
```{r}
library(rjd3toolkit)
library(rjd3tramoseats)
library(rjd3providers)
data<-file.path(rprojroot::find_root(rprojroot::is_rstudio_project ), 'Data')
set_spreadsheet_paths(data)
xs<-spreadsheet_data("Belgium_XM.xlsx", 1)$series
ms<-spreadsheet_data("Belgium_XM.xlsx", 2)$series
s<-ABS$X0.2.20.10.M
```

# Calendars

### Trading days

```{r}
td_raw<-td(s=s, contrasts=FALSE)
colnames(td_raw)<-c("Sundays", "Mondays", "Tuesdays", "Wednesdays", "Thursdays", "Fridays", "Saturdays")
print(window(td_raw, start=c(2000,1), end=c(2001,12)))
model1<-sarima_estimate(log(s), order=c(0,1,1), seasonal=list(order=c(0,1,1), period=12), xreg = td_raw)
print(model1)
cat("\nAverage effect:", mean(model1$b), "\n\n")

lp<-lp_variable(s=s, type = "LengthOfPeriod")
td2<-cbind(td_raw[,-1]-td_raw[,1], lp)
colnames(td2)<-c("Mondays", "Tuesdays", "Wednesdays", "Thursdays", "Fridays", "Saturdays", "lp")
print(window(td2, start=c(2000,1), end=c(2001,12)))
model2<-sarima_estimate(log(s), order=c(0,1,1), seasonal=list(order=c(0,1,1), period=12), xreg = td2)
print(model2)
print(model1$b[-1]-model2$b[-7])
print(-sum(model2$b[1:6]))
dlp<-model2$b[7]-mean(model1$b)
print(dlp)


lp<-lp_variable(s=s, type = "LeapYear")
td3<-cbind(td_raw[,-5]-td_raw[,5], lp)
colnames(td3)<-c("Sundays", "Mondays", "Tuesdays", "Wednesdays", "Fridays", "Saturdays", "lp")
print(window(td3, start=c(2000,1), end=c(2001,12)))
model3<-sarima_estimate(log(s), order=c(0,1,1), seasonal=list(order=c(0,1,1), period=12), xreg = td3)
print(model3)

print(model1$b-mean(model1$b))
print(model2$b)
print(model3$b)
print(-sum(model3$b[1:6]))
```

